package constants

// 日志模板集中定义，业务字段变更时必须同步修改对应模板与调用处。
var LogTemplates = map[string]string{
	"user_login_ok":          "user login success, username=%s, role=%s",
	"user_login_fail":        "user login failed, username=%s, err=%s",
	"user_register_ok":       "user register success, username=%s, role=%s",
	"user_create_ok":         "admin create user success, username=%s, role=%s",
	"user_update_ok":         "user update success, userID=%d, field=%s",
	"user_delete_ok":         "user delete success, userID=%d",
	"station_create_ok":      "station create success, stationName=%s, area=%s",
	"station_update_ok":      "station update success, stationID=%d, field=%s",
	"station_status_change":  "station status change, stationID=%d, from=%s, to=%s, operator=%s",
	"station_delete_ok":      "station delete success, stationID=%d",
	"recharge_create_ok":     "member recharge success, userID=%d, amount=%f, method=%s",
	"package_order_ok":       "package order success, userID=%d, packageID=%d, amount=%f",
	"user_package_credit":    "user package credit, userID=%d, packageID=%d, hours=%f",
	"reservation_create_ok":  "reservation create success, userID=%d, stationID=%d, start=%s",
	"reservation_confirm_ok": "reservation confirm success, reservationID=%d",
	"reservation_cancel_ok":  "reservation cancel success, reservationID=%d",
	"reservation_checkin_ok": "reservation checkin success, reservationID=%d",
	"session_start_ok":       "session start success, userID=%d, stationID=%d, sessionID=%d",
	"session_renew_ok":       "session renew success, sessionID=%d, addMinutes=%d",
	"session_end_ok":         "session end success, sessionID=%d, duration=%d, amount=%f",
	"session_rank_query":     "session rank query, period=%s, gameType=%s",
	"tournament_create_ok":   "tournament create success, tournamentID=%d, name=%s",
	"tournament_publish_ok":  "tournament publish success, tournamentID=%d",
	"tournament_draw_ok":     "tournament draw success, tournamentID=%d, groups=%d",
	"registration_create_ok": "registration create success, tournamentID=%d, mode=%s",
	"match_result_ok":        "match result submit success, matchID=%d, winnerID=%d",
	"audit_write_ok":         "audit log write success, action=%s, module=%s",
}
